# -*- coding: utf-8 -*-
"""gc_homeland_v4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-eQgm0kPyKsjSglcFutVCEYgY6iLM2_L
"""

! pip install pytesseract
! apt-get install poppler-utils
! pip install pdf2image
! apt install tesseract-ocr
! apt install libtesseract-dev
! get install opencv
! pip install easyocr
# # !apt-get -qq install -y libsm6 libxext6 && pip install -q -U opencv-python

import pdf2image
from pdf2image import convert_from_path
import easyocr
import numpy as np
import PIL
from PIL import ImageDraw
import spacy

from IPython.display import display, Image

import os
import tempfile
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2

# 'en' = English
# 'id' = Indonesia
reader = easyocr.Reader(['en'])

from google.colab import files
uploaded = files.upload()

images = convert_from_path('functionalSample.pdf')

display(images[0])

"""### Creating Bounding Box"""

bounds = reader.readtext(np.array(images[0]), min_size=0, slope_ths=0.2, 
                         ycenter_ths=0.7, height_ths=0.6, width_ths=0.8,
                         decoder='beamsearch', beamWidth=10)
bounds

## Function creating bounding box for 

def draw_boxes(image, bounds, color='green', width=2):
  draw = ImageDraw.Draw(image)
  for bound in bounds:
    p0, p1, p2, p3 = bound[0] #every angle of the bounding box
    draw.line([*p0, *p1, *p2, *p3, *p0], fill=color, width=width)
  return image

draw_boxes(images[0], bounds)

